---
title: "Antibody titer analysis"
author: "ten-Caten, Felipe - ftencat@emory.edu"
editor_options: 
  chunk_output_type: console
output: github_document
---

```{r Load libraries}
library(tidyverse)
library(rstatix)
library(ggpubr)
library(MultiAssayExperiment)
library(ggfortify)
library(limma)
```

```{r Load files}
#ds.mae <- readRDS('data/processed_multiassay_experiment/ds_ijc_multiassay.rds')
ds.mae <- readRDS('data/processed_multiassay_experiment/ds_ijc_multiassay_20240507.rds')

pheno <- as.data.frame(colData(ds.mae))

abs.raw <- ds.mae[['Antibodies']] 

#colData(ds.mae[['Metabolites']])
```

```{r Pre-processing}
sfun <- function(x) { 
  x <- na.omit(x)
  if (all(x>=0)) NA else max(x[x<0]) 
}

abs.df <- t(abs.raw) %>% 
  as.data.frame() %>% 
  rownames_to_column('sampleid') %>% 
  mutate(across(-sampleid, ~as.numeric(.)))

abs.pheno <- abs.df %>% 
  mutate(patientid = sub('_.*', '', sampleid))  |> 
  left_join(pheno %>% 
              rownames_to_column('patientid') %>% 
              select(patientid, ds, age_years, sex, Visit.1.date, Visit.2.date, 
                     starts_with('X'))) |> 
  mutate(visit = sub('.*_','',  sampleid)) |> 
  relocate(sampleid, visit) |> 
  mutate(Visit.date = case_when(visit == 'V1' ~ `Visit.1.date`, 
                                TRUE ~ `Visit.2.date`)) |> 
  select(-c(`Visit.1.date`, `Visit.2.date`)) |> 
  mutate(`interval_visit_1st_infec_days` = time_length(interval(Visit.date, 
                                                    X1st.infection.date), unit = 'days'),
         `interval_visit_2nd_infec_days` = time_length(interval(Visit.date, 
                                                    X2nd.infection.date), unit = 'days'),
         `interval_visit_from_1st_vacc_days` = time_length(interval(Visit.date, 
                                                    X1st.vacc..dose.date), unit = 'days'),
         `interval_visit_from_2nd_vacc_days` = time_length(interval(Visit.date, 
                                                    X2nd.vacc..dose.date), unit = 'days'),
         `interval_visit_from_3rd_vacc_days` = time_length(interval(Visit.date, 
                                                    X3rd.vacc..dose.date), unit = 'days'),
         `interval_visit_from_4th_vacc_days` = time_length(interval(Visit.date, 
                                                    X4th.vacc..dose.date), unit = 'days'),
         `interval_visit_from_5th_vacc_days` = time_length(interval(Visit.date, 
                                                    X5th.vacc..dose.date), unit = 'days')) |> 
  rowwise() %>%
  mutate(most_recent_event = sfun(c_across(ends_with('c_days'))),
         number_events = sum(c_across(ends_with('c_days')) < 0, na.rm = T)) %>%
  ungroup() |> 
  mutate(infection = ifelse(is.na(X1st.infection.date), 'no', 'yes')) 
```

```{r Exploratory PCA}
pca.visit <- autoplot(prcomp(log1p(abs.pheno[,3:10])), 
                      data = abs.pheno, shape = 21,
                      fill = 'visit', size = 3)

#ggsave('results/antibodies/pca_visit.pdf', pca.visit, width = 5.5, height = 5)

pca.ds <-autoplot(prcomp(log1p(abs.pheno[,3:10])), 
                  data = abs.pheno, shape = 21, fill = 'ds', size = 3) +
  scale_fill_manual(values= c('darkblue', 'yellow'))

#ggsave('results/antibodies/pca_downsyndrome.pdf', pca.ds, width = 5.5, height = 5)
```

```{r Linear regression - DS}
### VISIT 1
abs.pheno.v1 <- abs.pheno |> 
  filter(visit == 'V1') |> 
  column_to_rownames('sampleid') |> 
  filter(!is.na(most_recent_event), !is.na(number_events))

ds <- abs.pheno.v1$ds
antigen_exposure_days <- abs(abs.pheno.v1$most_recent_event)
number_exposures <- abs.pheno.v1$number_events

design <- model.matrix(~ ds + antigen_exposure_days)

fit <- lmFit( t(log1p(abs.pheno.v1[,2:9])), design=design)
fit <- eBayes(fit)

topTable(fit, coef = 'dsyes')

# Filter by days + # antigen exposure + no infection
abs.pheno.v1 <- abs.pheno |> 
  filter(visit == 'V1', most_recent_event >= -90, 
         infection == 'no', number_events == 2) |> 
  column_to_rownames('sampleid') |> 
  filter(!is.na(most_recent_event), !is.na(number_events))

ds <- abs.pheno.v1$ds

design <- model.matrix(~ ds )

fit <- lmFit( t(log1p(abs.pheno.v1[,2:9])), design=design)
fit <- eBayes(fit)

abs.v1.stat <- topTable(fit, coef = 'dsyes')

## VISIT 2
abs.pheno.v2 <- abs.pheno |> 
  filter(visit == 'V2', most_recent_event >= -90, 
         infection == 'no', number_events == 3) |> 
  column_to_rownames('sampleid') |> 
  filter(!is.na(most_recent_event), !is.na(number_events))

ds <- abs.pheno.v2$ds
antigen_exposure_days <- abs(abs.pheno.v2$most_recent_event)
number_exposures <- abs.pheno.v2$number_events

design <- model.matrix(~ ds + antigen_exposure_days)

fit <- lmFit( t(log1p(abs.pheno.v2[,2:9])), design=design)
fit <- eBayes(fit)

topTable(fit, coef = 'dsyes')

# Filter by days + # antigen exposure + no infection
abs.pheno.v2 <- abs.pheno |> 
  filter(visit == 'V2', most_recent_event >= -90, 
         infection == 'no', number_events == 3) |> 
  column_to_rownames('sampleid') |> 
  filter(!is.na(most_recent_event), !is.na(number_events))

ds <- abs.pheno.v2$ds

design <- model.matrix(~ ds )

fit <- lmFit( t(log1p(abs.pheno.v2[,2:9])), design=design)
fit <- eBayes(fit)

abs.v2.stat <- topTable(fit, coef = 'dsyes')
```

```{r Plots}
density.days <- abs.pheno |> 
  ggplot(aes(x = abs(most_recent_event), fill = ds)) +
  geom_density(alpha = 0.6) +
  scale_fill_manual(values = c('darkblue', 'yellow'), name = 'Group',
                    labels = c('non-DS', 'DS')) +
  xlim(c(0,400))+
  facet_wrap(~visit) +
  labs(x = 'Days from antigen exposure') +
  theme(axis.title = element_text(size = 13),
        axis.text = element_text(size = 11))

#ggsave('results/antibodies/densityplot_days_antigens_exposure.pdf',
#       density.days, scale = 0.5)

abs.tidy <- abs.pheno |> 
  mutate(infection = ifelse(is.na(X1st.infection.date), 'no', 'yes')) |> 
  select(sampleid, visit, starts_with('SARS'), starts_with('Spike'),
         ds, age_years, sex, infection, most_recent_event, number_events) |> 
  pivot_longer(-c(sampleid, visit, ds, age_years, sex, infection, 
                  most_recent_event, number_events), 
               names_to = 'antibody', values_to = 'titer')

sub.v2 <- abs.tidy |> 
  filter(visit == 'V2', most_recent_event >= -90, 
         infection == 'no', number_events == 3) |> 
  pivot_wider(names_from = 'antibody', values_from = 'titer')


#write_tsv(sub.v2, 'results/antibodies/selected_patients_visit2_40.tsv')

abs.v1 <- abs.tidy |> 
  filter(visit == 'V1') |> 
  ggplot(aes(x = ds, y = titer, fill = ds))+
  geom_boxplot(outlier.shape = NA, alpha = 0.7, ) +
  geom_jitter(shape = 21, width = 0.05) +
  facet_wrap(~antibody, scales = 'free_y') +
  scale_y_continuous(transform = 'log10') +
  scale_fill_manual(values = c('darkblue', 'yellow'), guide = 'none') +
  scale_x_discrete(labels = c('non-DS', 'DS')) +
  labs(x = '') +
  ggtitle('Visit 1')

#ggsave('results/antibodies/boxplot_v1_titers.pdf', abs.v1, width = 7, height = 7)


abs.v2 <- abs.tidy |> 
  filter(visit == 'V2') |> 
  ggplot(aes(x = ds, y = titer, fill = ds))+
  geom_boxplot(outlier.shape = NA, alpha = 0.7, ) +
  geom_jitter(shape = 21, width = 0.05) +
  facet_wrap(~antibody, scales = 'free_y') +
  scale_y_continuous(transform = 'log10') +
  scale_fill_manual(values = c('darkblue', 'yellow'), guide = 'none') +
  scale_x_discrete(labels = c('non-DS', 'DS')) +
  labs(x = '') +
  ggtitle('Visit 2')

#ggsave('results/antibodies/boxplot_v2_titers.pdf', abs.v2, width = 7, height = 7)

nucleocapsid.v1.v2 <- abs.tidy |> 
  filter(antibody == 'SARS-CoV2 Nucleocapsid') |> 
  ggplot(aes(x = visit, y = titer, fill = ds))+
  geom_boxplot(outlier.shape = NA, alpha = 0.7, ) +
  geom_point(shape = 21, 
             position = position_jitterdodge(jitter.width = 0.05)) +
  scale_y_continuous(transform = 'log10') +
  geom_smooth(method = 'lm', aes(group = ds, colour = ds), se = F, linewidth = 2) +
  scale_fill_manual(values = c('darkblue', 'yellow'), name = 'Group',
                    labels = c('non-DS', 'DS')) +
  scale_colour_manual(values = c('darkblue', '#CCCC00'), name = 'Group',
                    labels = c('non-DS', 'DS')) +
  labs(x = '') +
  ggtitle('SARS-CoV2 Nucleocapsid')

#ggsave('results/antibodies/boxplot_v1_v2_nucleocapsid_titers.pdf', 
#       nucleocapsid.v1.v2, width = 6.66, height = 4)

## Filter 90 days + No infection + # Exposures
abs.v1.stat.p <- abs.v1.stat |> 
  rownames_to_column('antibody') |> 
  mutate(group1 = 'no', group2 = 'yes', y.position = 5.7) |> 
  mutate(P.Value = round(P.Value, digits = 3)) |> 
  dplyr::rename(p = P.Value) |> 
  select(antibody, group1, group2, y.position, p)

abs.v1.d90  <- abs.tidy |> 
  filter(visit == 'V1', most_recent_event >= -90, 
         infection == 'no', number_events == 2) |> 
  ggplot(aes(x = ds, y = titer))+
  geom_boxplot(outlier.shape = NA, alpha = 0.7, aes(fill = ds)) +
  geom_jitter(shape = 21, width = 0.05, aes(fill = ds)) +
  facet_wrap(~antibody, scales = 'free_y') +
  stat_pvalue_manual(abs.v1.stat.p) +
  scale_y_continuous(transform = 'log10',
                     expand = expansion(mult = c(0.05, 0.15))) +
  scale_fill_manual(values = c('darkblue', 'yellow'), guide = 'none') +
  scale_x_discrete(labels = c('non-DS', 'DS')) +
  labs(x = '') +
  ggtitle('Visit 1 - Antigen exposure up to 90 days + 2 vaccines + No infection')

#ggsave('results/antibodies/boxplot_v1_titers_90days_noinfection_2vacc.pdf', 
#       abs.v1.d90, width = 7, height = 7)

abs.v2.stat.p <- abs.v2.stat |> 
  rownames_to_column('antibody') |> 
  mutate(group1 = 'no', group2 = 'yes', y.position = 6.5) |> 
  mutate(P.Value = round(P.Value, digits = 3)) |> 
  dplyr::rename(p = P.Value) |> 
  select(antibody, group1, group2, y.position, p)

abs.v2.d90  <- abs.tidy |> 
  filter(visit == 'V2', most_recent_event >= -90, 
         infection == 'no', number_events == 3) 
  ggplot(aes(x = ds, y = titer))+
  geom_boxplot(outlier.shape = NA, alpha = 0.7,  aes( fill = ds)) +
  geom_jitter(shape = 21, width = 0.05, aes( fill = ds)) +
  facet_wrap(~antibody, scales = 'free_y') +
  scale_y_continuous(transform = 'log10',
                     expand = expansion(mult = c(0.05, 0.15))) +
  stat_pvalue_manual(abs.v2.stat.p) +
  scale_fill_manual(values = c('darkblue', 'yellow'), guide = 'none') +
  scale_x_discrete(labels = c('non-DS', 'DS')) +
  labs(x = '') +
  ggtitle('Visit 2 - Antigen exposure up to 90 days + 3 vaccines + No infection')

#ggsave('results/antibodies/boxplot_v2_titers_90days_noinfection_3vacc.pdf', 
#       abs.v2.d90, width = 7, height = 7)
```

```{r Linear regression - ABs (Spike)}
sub.v2 <- read_tsv('results/antibodies/selected_patients_visit2_40.tsv')

metab.raw <- ds.mae[['Metabolites']] 

sub.metab <- metab.raw[,sub.v2$sampleid]

metabs.to.keep <- which(rowMeans(is.na(assay(sub.metab))) <= 1/3)

sub.metab.v2 <- sub.metab[names(metabs.to.keep),]

sub.v2.sorted <- sub.v2 |> 
  column_to_rownames('sampleid')

spike <- log2(sub.v2.sorted[colnames(sub.metab.v2), 'SARS-CoV2 Spike'])

design <- model.matrix(~ spike)

fit <- lmFit(assay(sub.metab.v2), design=design)
fit <- eBayes(fit)

out <- topTable(fit, coef = 'spike', sort.by = 'p', n=Inf)

out.name <- out |> 
  rownames_to_column('metabid') |> 
  left_join(as.data.frame(rowData(metab.raw)) |> 
              rownames_to_column('metabid') |>
              select(metabid, PLOT_NAME, SUB_PATHWAY))


x <- assay(sub.metab.v2) |> 
  t() |> 
  as.data.frame() |> 
  rownames_to_column('sampleid') |> 
  left_join(sub.v2 |> select(sampleid, `SARS-CoV2 Spike`)) |> 
  cor_test(vars = `SARS-CoV2 Spike`, method = 'spearman') |> 
  adjust_pvalue(p.col = 'p', method = 'BH') |> 
  arrange(p)
  
```



### Old analysis

```{r Initial Plots}
pheno.days %>% 
  filter(is.na(sarscov2_infection_1st_date)) %>% 
  ggplot(aes(x = visit_1_from_boost_days)) + 
  geom_histogram() +
  facet_wrap(~ds) +
  xlab('Visit 1 - Days from boost')

pheno.days %>% 
  filter(is.na(sarscov2_infection_1st_date)) %>% 
  ggplot(aes(x = visit_2_from_boost_days)) + 
  geom_histogram() +
  facet_wrap(~ds) +
  xlab('Visit 2 - Days from boost')

pheno.days %>% filter(is.na(sarscov2_infection_1st_date), ds == 'no') %>% nrow()

## Visit 2
visit2_from_boost <- abs.pheno %>% 
  filter(grepl('_V2', sampleid), is.na(sarscov2_infection_1st_date)) %>% 
  filter(visit_2_from_boost_days < -180,
         visit_2_from_boost_days > -365) %>% 
  pivot_longer(-c(patientid, ds, age_years, sex, sarscov2_infection_1st_date,
           visit_1_from_boost_days, visit_2_from_boost_days, sampleid, 
           infect_first_days))

visit2_from_boost.stat <- visit2_from_boost %>% 
  group_by(name) %>% 
  wilcox_test(value ~ ds) %>% 
  adjust_pvalue(p.col = 'p', method = 'BH') %>% 
  add_xy_position(y.trans = log10, step.increase = 0.2) %>% 
  add_significance(p.col = 'p.adj')

visit2_from_boost.plot <- visit2_from_boost %>% 
  ggplot(aes(x = ds, y = value)) +
  geom_boxplot(aes(fill = ds), alpha = 0.7, width = 0.4) +
  geom_jitter(aes(fill = ds), width = 0.05, shape = 21)+
  scale_y_continuous(trans = 'log10',
                     expand = expansion(mult = c(0.05, 0.12))) +
  facet_wrap(~name) +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"),
                    name = 'Group', labels = c('HC', 'DS')) +
  stat_pvalue_manual(visit2_from_boost.stat, label = "p.adj.signif", size = 6, 
                     bracket.nudge.y = 0.3) +
  labs(x = '', y = 'Antibody levels') +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  ggtitle('Visit 2 - Non-infected - 6-12m after boost')
  
#ggsave('results/antibodies/boxplot_abs_titer_visit2_noninfected_6-12m_after_boost.pdf',
#       visit2_from_boost.plot, device = 'pdf', width = 5.3, height = 5)

## Visit 1
visit1_from_boost <- abs.pheno %>% 
  filter(grepl('_V1', sampleid), is.na(sarscov2_infection_1st_date)) %>% 
  filter(visit_1_from_boost_days > -180) %>% 
  pivot_longer(-c(patientid, ds, age_years, sex, sarscov2_infection_1st_date,
           visit_1_from_boost_days, visit_2_from_boost_days, sampleid, 
           infect_first_days))

visit1_from_boost.stat <- visit1_from_boost %>% 
  group_by(name) %>% 
  wilcox_test(value ~ ds) %>% 
  adjust_pvalue(p.col = 'p', method = 'BH') %>% 
  add_xy_position(y.trans = log10, step.increase = 0.2) %>% 
  add_significance(p.col = 'p.adj')

visit1_from_boost.plot <- visit1_from_boost %>% 
  ggplot(aes(x = ds, y = value)) +
  geom_boxplot(aes(fill = ds), alpha = 0.7, width = 0.4) +
  geom_jitter(aes(fill = ds), width = 0.05, shape = 21)+
  scale_y_continuous(trans = 'log10',
                     expand = expansion(mult = c(0.05, 0.15))) +
  facet_wrap(~name) +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"),
                    name = 'Group', labels = c('HC', 'DS')) +
  stat_pvalue_manual(visit1_from_boost.stat, label = "p.adj.signif", size = 6, 
                     bracket.nudge.y = 0.3) +
  labs(x = '', y = 'Antibody levels') +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  ggtitle('Visit 1 - Non-infected - 0-6m after boost')
  
#ggsave('results/antibodies/boxplot_abs_titer_visit1_noninfected_0-6m_after_boost.pdf',
#       visit1_from_boost.plot, device = 'pdf', width = 5.3, height = 5)

## Visit 2 all patients
visit2 <- abs.pheno %>% 
  filter(grepl('_V2', sampleid)) %>% 
  pivot_longer(-c(patientid, ds, age_years, sex, sarscov2_infection_1st_date,
           visit_1_from_boost_days, visit_2_from_boost_days, sampleid,
           infect_first_days))

visit2.stat <- visit2 %>% 
  group_by(name) %>% 
  wilcox_test(value ~ ds) %>% 
  adjust_pvalue(p.col = 'p', method = 'BH') %>% 
  add_xy_position(y.trans = log10, step.increase = 0.2) %>% 
  add_significance(p.col = 'p.adj')

visit2.plot <- visit2 %>% 
  ggplot(aes(x = ds, y = value)) +
  geom_boxplot(aes(fill = ds), alpha = 0.7, width = 0.4) +
  geom_jitter(aes(fill = ds), width = 0.05, shape = 21)+
  scale_y_continuous(trans = 'log10',
                     expand = expansion(mult = c(0.05, 0.12))) +
  facet_wrap(~name) +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"),
                    name = 'Group', labels = c('HC', 'DS')) +
  stat_pvalue_manual(visit2.stat, label = "p.adj.signif", size = 6, 
                     bracket.nudge.y = 0.3) +
  labs(x = '', y = 'Antibody levels') +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  ggtitle('Visit 2')

### Infected visit 2
visit2_from_boost.infct <- abs.pheno %>% 
  filter(grepl('_V2', sampleid), !is.na(sarscov2_infection_1st_date)) %>% 
  filter(!is.na(visit_2_from_boost_days)) %>% 
  pivot_longer(-c(patientid, ds, age_years, sex, sarscov2_infection_1st_date,
           visit_1_from_boost_days, visit_2_from_boost_days, sampleid,
           infect_first_days))

visit2_from_boost.infct.stat <- visit2_from_boost.infct %>% 
  group_by(name) %>% 
  wilcox_test(value ~ ds) %>% 
  adjust_pvalue(p.col = 'p', method = 'BH') %>% 
  add_xy_position(y.trans = log10, step.increase = 0.2) %>% 
  add_significance(p.col = 'p.adj')

visit2_from_boost.infect.plot <- visit2_from_boost.infct %>% 
  ggplot(aes(x = ds, y = value)) +
  geom_boxplot(aes(fill = ds), alpha = 0.7, width = 0.4) +
  geom_jitter(aes(fill = ds), width = 0.05, shape = 21)+
  scale_y_continuous(trans = 'log10',
                     expand = expansion(mult = c(0.05, 0.12))) +
  facet_wrap(~name) +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"),
                    name = 'Group', labels = c('HC', 'DS')) +
  stat_pvalue_manual(visit2_from_boost.infct.stat, label = "p.adj.signif", size = 6, 
                     bracket.nudge.y = 0.3) +
  labs(x = '', y = 'Antibody levels') +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  ggtitle('Visit 2 - Infected')
  
#ggsave('results/antibodies/boxplot_abs_titer_visit2_Infected.pdf',
#       visit2_from_boost.infect.plot, device = 'pdf', width = 5.3, height = 5)
```

```{r Days post boost - Dotplot}
data <- abs.pheno %>% 
  filter(!(patientid %in% c('SMP', 371, 181)), !is.na(visit_1_from_boost_days)) %>% 
  pivot_longer(-c(patientid, ds, age_years, sex, sarscov2_infection_1st_date,
           visit_1_from_boost_days, visit_2_from_boost_days, sampleid,
           infect_first_days)) %>% 
  filter(!is.na(value)) %>% 
  mutate(visit = sub('.*_', '', sampleid)) %>% 
  mutate(days_from_boost = ifelse(visit == 'V1', visit_1_from_boost_days,
                                  visit_2_from_boost_days))  %>% 
  filter(is.na(infect_first_days)) %>% 
  mutate(lm.group = case_when(ds == 'no' & visit_1_from_boost_days > -100 ~ 'HC.early',
                              ds == 'no' & visit_1_from_boost_days < -100 ~ 'HC.late',
                              ds == 'yes' ~ 'DS'))

visit1visit2.plot <- data %>% 
  ggplot(aes(y = value, x = visit)) +
  geom_point(aes(fill = ds), shape = 21, 
             position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.5)) +
  geom_smooth(aes(group = ds, color = ds), method='lm', formula= y~x, se = F) +
  scale_y_continuous(trans = 'log10') +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"),
                    name = 'Group', labels = c('HC', 'DS')) +
  scale_color_manual(values = c("#0D0887FF", "#F0F921FF"), guide = 'none') +
  facet_wrap(~name) +
  labs(x = 'Visit', y = 'Antibody levels') +
  theme_bw()

#ggsave('results/antibodies/dotplot_abs_titer_visit1_visit2.pdf',
#       visit1visit2.plot, device = 'pdf', width = 5.3, height = 5)

days.from.boost.plot <- data %>% 
  ggplot(aes(y = value, x = days_from_boost*-1)) +
  geom_line(aes(group = patientid, linetype = ds), alpha = 0.1) +
  geom_point(aes(fill = ds, shape = visit), size = 2, alpha = 0.8) +
  scale_y_continuous(trans = 'log10') +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"),
                    name = 'Group', labels = c('HC', 'DS')) +
  scale_linetype(name = 'Group', labels = c('HC', 'DS')) +
  scale_shape_manual(values = c(21,22)) +
  facet_wrap(~name) +
  labs(x = 'Days post boost', y = 'Antibody levels') +
  guides(fill = guide_legend(override.aes=list(shape = 21))) +
   theme_bw() +
  theme(panel.grid.minor = element_blank())

#ggsave('results/antibodies/dotplot_days_from_boost.pdf',
#       days.from.boost.plot, device = 'pdf', scale = 0.9)


x <- data %>% filter(name == 'RBD (P.1)') %>% 
  mutate(days_from_boost = days_from_boost*-1,
         infect_first_days = infect_first_days*-1) %>% 
  mutate(log10.value = log10(value)) 

summary(lm(log10.value ~ ds*days_from_boost, data = x))

model <- lmer(log10.value  ~ ds*days_from_boost + (1|patientid), data = x)
car::Anova(model)

model <- lme(log10.value  ~ ds*days_from_boost, random=~1|patientid, data = x)

model.result <- data %>% 
  mutate(days_from_boost = days_from_boost*-1,
         infect_first_days = infect_first_days*-1) %>% 
  mutate(log10.value = log10(value)) %>% 
  filter(is.na(infect_first_days)) %>% 
  group_by(name) %>% 
  do(tidy(lm(log10.value ~ ds*days_from_boost, .)))
```

```{r Comparison V1 and V2 - boost non-infected only - same timepoints}
data <- abs.pheno %>% 
  filter(!(patientid %in% c('SMP', 371, 181)), !is.na(visit_1_from_boost_days)) %>% 
  pivot_longer(-c(patientid, ds, age_years, sex, sarscov2_infection_1st_date,
           visit_1_from_boost_days, visit_2_from_boost_days, sampleid,
           infect_first_days)) %>% 
  filter(!is.na(value)) %>% 
  mutate(visit = sub('.*_', '', sampleid)) %>% 
  mutate(days_from_boost = ifelse(visit == 'V1', visit_1_from_boost_days,
                                  visit_2_from_boost_days))  %>% 
  filter(is.na(infect_first_days)) %>% 
  filter(visit_1_from_boost_days > -100)

data.stat <- data %>% 
  filter(name != 'SARS-Cov-2 N') %>% 
  group_by(ds, name) %>% 
  wilcox_test(value ~ visit) %>% 
  adjust_pvalue(p.col = 'p', method = 'BH') %>% 
  add_xy_position() %>% 
  mutate(xmin = ifelse(ds == 'no', xmin - 0.19, xmin + 0.19),
         xmax = ifelse(ds == 'no', xmax - 0.19, xmax + 0.19),
         y.position = log10(y.position))

compare_visit1_visit2 <- data %>% 
  filter(name != 'SARS-Cov-2 N') %>% 
  ggplot(aes(x = visit, y = value, fill = ds)) +
  geom_boxplot(alpha = 0.8) +
  geom_jitter(shape = 21, 
              position = position_jitterdodge(jitter.width = 0.1)) +
  stat_pvalue_manual(data.stat, 
                     label = "p = {scales::pvalue(p.adj)}")+
  facet_wrap(~name) +
  scale_y_continuous(trans = 'log10', expand = expansion(mult = c(0.05, 0.25))) +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"),
                    name = 'Group', labels = c('HC', 'DS')) +
  labs(x = 'Visit', y = 'ABs Titer') +
  theme_bw()

#ggsave('results/antibodies/boxplot_visits_comparison.pdf',
#       compare_visit1_visit2, device = 'pdf', height = 5.5, width = 7)

days.post.boost.same.days.plot <- data %>% 
  ggplot(aes(y = value, x = days_from_boost*-1)) +
  geom_line(aes(group = patientid, linetype = ds), alpha = 0.2) +
  geom_point(aes(fill = ds, shape = visit), size = 2, alpha = 0.8) +
  scale_y_continuous(trans = 'log10') +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"),
                    name = 'Group', labels = c('HC', 'DS')) +
  scale_linetype(name = 'Group', labels = c('HC', 'DS')) +
  scale_shape_manual(values = c(21,22)) +
  facet_wrap(~name) +
  labs(x = 'Days post boost', y = 'Antibody levels') +
  guides(fill = guide_legend(override.aes=list(shape = 21))) +
   theme_bw() +
  theme(panel.grid.minor = element_blank())

#ggsave('results/antibodies/dotplot_days_post_boost_same_days.pdf',
#       days.post.boost.same.days.plot, device = 'pdf', scale = 0.8)

## Visit 1
visit1_post_boost <- data %>% 
  filter(visit == 'V1')

visit1_post_boost.stat <- visit1_post_boost %>% 
  group_by(name) %>% 
  wilcox_test(value ~ ds) %>% 
  adjust_pvalue(p.col = 'p', method = 'BH') %>% 
  add_xy_position(y.trans = log10, step.increase = 0.2) %>% 
  add_significance(p.col = 'p.adj')

visit1_post_boost.plot <- visit1_post_boost %>% 
  ggplot(aes(x = ds, y = value)) +
  geom_boxplot(aes(fill = ds), alpha = 0.7, width = 0.4, outlier.shape = NA) +
  geom_jitter(aes(fill = ds), width = 0.05, shape = 21)+
  scale_y_continuous(trans = 'log10',
                     expand = expansion(mult = c(0.05, 0.18))) +
  facet_wrap(~name) +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"),
                    name = 'Group', labels = c('HC', 'DS')) +
  stat_pvalue_manual(visit1_post_boost.stat, size = 4, 
                     bracket.nudge.y = 0.3, vjust = -0.3,
                     label = "p.adj = {scales::pvalue(p.adj)}") +
  labs(x = '', y = 'Antibody levels') +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  ggtitle('Visit 1 - Non-infected')

#ggsave('results/antibodies/boxplot_abs_titer_visit1_noninfected.pdf',
#       visit1_post_boost.plot, device = 'pdf', width = 5.3, height = 5)

## Visit 2
visit2_post_boost <- data %>% 
  filter(visit == 'V2')

visit2_post_boost.stat <- visit2_post_boost %>% 
  group_by(name) %>% 
  wilcox_test(value ~ ds) %>% 
  adjust_pvalue(p.col = 'p', method = 'BH') %>% 
  add_xy_position(y.trans = log10, step.increase = 0.2) %>% 
  add_significance(p.col = 'p.adj')

visit2_post_boost.plot <- visit2_post_boost %>% 
  ggplot(aes(x = ds, y = value)) +
  geom_boxplot(aes(fill = ds), alpha = 0.7, width = 0.4, outlier.shape = NA) +
  geom_jitter(aes(fill = ds), width = 0.05, shape = 21)+
  scale_y_continuous(trans = 'log10',
                     expand = expansion(mult = c(0.05, 0.18))) +
  facet_wrap(~name) +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"),
                    name = 'Group', labels = c('HC', 'DS')) +
  stat_pvalue_manual(visit2_post_boost.stat, size = 4, 
                     bracket.nudge.y = 0.3, vjust = -0.3,
                     label = "p.adj = {scales::pvalue(p.adj)}") +
  labs(x = '', y = 'Antibody levels') +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  ggtitle('Visit2 - Non-infected')

#ggsave('results/antibodies/boxplot_abs_titer_visit2_noninfected.pdf',
#       visit2_post_boost.plot, device = 'pdf', width = 5.3, height = 5)

#write_tsv(visit2_post_boost.plot$data, 
#          'results/antibodies/boxplot_abs_titer_visit2_noninfected_data.tsv')
```

