---
title: "R Notebook"
editor_options: 
  chunk_output_type: console
---

```{r Load libraries}
library(MultiAssayExperiment)
library(tidyverse)
library(rstatix)
library(limma)
library(ComplexHeatmap)
```

```{r Load files}
ds.mae <- readRDS('data/processed_multiassay_experiment/ds_ijc_multiassay_20240507.rds')

sub.v2 <- read_tsv('results/antibodies/selected_patients_visit2_56.tsv')
```

```{r Pre-processing}
cytokines.raw <- ds.mae[['MSD.plasma']] |> 
  as.data.frame() |> 
  select(ends_with('_V2')) |> 
  rename_with(~sub('_V2', '', .))

pheno <- as.data.frame(colData(ds.mae)) |> 
  filter(!is.na(ds))
```

```{r PCA}
# Whole dataset
pca_plasma_visit2 <- prcomp(t(log1p(cytokines.raw)), scale. = T)

pca_plot_plasma_visit2 <- autoplot(pca_plasma_visit2, 
         data = pheno[colnames(cytokines.raw),], fill = 'ds', 
         shape = 21, size = 3, names = T, alpha = 0.8) +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"), name = 'Group',
                    labels = c('HC', 'DS')) +
  ggtitle('PCA - Plasma Cytokines - Visit 2')+
  theme_bw()

ggsave('results/cytokines/figures/pca_plasma_cytokines_Visit2.pdf',
       pca_plot_plasma_visit2, device = 'pdf', scale = 0.5)

## identify outliers
mt::pca.outlier(t(log1p(cytokines.raw)))

#  56 patients subset
cytokines.raw.subset <- cytokines.raw[, sub('_V2', '', sub.v2$sampleid)]

pca_plasma_visit2 <- prcomp(t(log1p(cytokines.raw.subset)), scale. = T)

pca_plot_plasma_visit2.subset <- autoplot(pca_plasma_visit2, 
         data = pheno[colnames(cytokines.raw.subset),], fill = 'ds', 
         shape = 21, size = 3, names = T, alpha = 0.8) +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"), name = 'Group',
                    labels = c('HC', 'DS')) +
  ggtitle('PCA - Plasma Cytokines - Visit 2 - 56 patients')+
  theme_bw()

ggsave('results/cytokines/figures/pca_plasma_cytokines_Visit2_subset.pdf',
       pca_plot_plasma_visit2.subset, device = 'pdf', scale = 0.5)

## identify outliers subset
mt::pca.outlier(t(log1p(cytokines.raw.subset)))
```

```{r Linear regression - DS}
# prepare eset
cytokines.raw <- ds.mae[['MSD.plasma']] |> 
  as.data.frame() |> 
  select(ends_with('_V2')) |> 
  rename_with(~sub('_V2', '', .))

pheno <- as.data.frame(colData(ds.mae)) |> 
  filter(!is.na(ds)) |> 
  mutate(most_recent_event = abs(most_recent_event))

eset <- ExpressionSet(assayData = as.matrix(log1p(cytokines.raw[,rownames(pheno)])),
                      phenoData = AnnotatedDataFrame(pheno))

# Whole dataset
design <- model.matrix(~ ds + age_years + sex + most_recent_event, data = pData(eset))

fit <- lmFit(eset[,rownames(design)], design = design)
fit <- eBayes(fit)

summary(decideTests(fit))

out <- topTable(fit, coef = 'dsyes', sort.by = 'p', n = Inf)

## Subset 56 patients
eset.subset <- eset[,sub('_V2', '', sub.v2$sampleid)]

design <- model.matrix(~ ds + age_years + sex + most_recent_event, 
                       data = pData(eset.subset))

fit <- lmFit(eset.subset, design = design)
fit <- eBayes(fit)

summary(decideTests(fit))

out <- topTable(fit, coef = 'dsyes', sort.by = 'p', n = Inf)

#write_tsv(out, 'results/cytokines/linear_regression_cytokines_56patients_DS_vs_nonDS.tsv')

signif.cytokines <- out |> 
  as.data.frame() |> 
  rownames_to_column('cytok') |> 
  filter(adj.P.Val < 0.05) |> 
  select(cytok) |> 
  deframe()

signif.cytokines.df <- t(scale(t(exprs(eset.subset)[signif.cytokines,])))

ds.vector <- ifelse(eset.subset$ds == 'no', 'non-DS', 'DS')

ha = HeatmapAnnotation(Group = ds.vector, 
                       col = list(Group = c("DS" = "yellow", "non-DS" = "darkblue")))

Heatmap(signif.cytokines.df, name = 'z-score', show_column_names = F, 
        top_annotation = ha, column_split = ds.vector)  
```

```{r Linear Model - age}
library(splines)
library(NbClust)
library(ComplexHeatmap)
library(fgsea)
library(clusterProfiler)

# prepare eset
cytokines.raw <- ds.mae[['MSD.plasma']] |> 
  as.data.frame() |> 
  select(ends_with('_V2')) 
  
cytok.keep <- names(which(rowMeans(cytokines.raw == 0) <= 1/3))

cytokines.raw <- cytokines.raw[cytok.keep,]

pheno <- colData(ds.mae) %>% 
  as.data.frame() %>% 
  rownames_to_column('patientid') |> 
  filter(!grepl('Control', patientid)) |> 
  mutate(sampleid = paste0(patientid, '_V2')) |> 
  dplyr::select(sampleid, patientid, ds, age_years, weight_kg, 
                height_meter, sex, most_recent_event, number_events, X1st.infection.date) |> 
  mutate(height_meter = ifelse(height_meter > 100, height_meter/100, height_meter)) %>% 
  mutate(bmi =  weight_kg/height_meter^2) %>% 
  mutate(bmi = ifelse(bmi == 0, NA, bmi)) %>% 
  mutate(bmi = ifelse(bmi == Inf, NA, bmi)) %>% 
  mutate(most_recent_event = abs(most_recent_event)) |> 
  mutate(most_recent_event = ifelse(is.na(most_recent_event), 750, most_recent_event)) |>
  mutate(infection = ifelse(is.na(X1st.infection.date), 'no', 'yes')) |> 
  column_to_rownames('sampleid') |> 
  mutate(ds = ifelse(ds == 'yes', 'ds', 'nonds')) |> 
  mutate(group = paste(ds, sex, sep = '.'))

eset <- ExpressionSet(assayData = as.matrix(log1p(cytokines.raw[,rownames(pheno)])),
                      phenoData = AnnotatedDataFrame(pheno))

## Linear
design1 <- model.matrix(~group+group:age_years+most_recent_event+0, pheno)
colnames(design1) <- make.names(colnames(design1))

fit <- lmFit(eset, design1)

cont.dif <- makeContrasts(groupds.Female.age_years - groupnonds.Female.age_years,
                          groupds.Female - groupnonds.Female,
                          groupds.Male.age_years - groupnonds.Male.age_years,
                          groupds.Male - groupnonds.Male,
                          levels = design1) 

fit2 <- contrasts.fit(fit, cont.dif)
fit2 <- eBayes(fit2) 

top.ds.age.female <- topTable(fit2, coef = 1:2, n = Inf, sort.by = "F")
top.ds.age.male <- topTable(fit2, coef = 3:4, n = Inf, sort.by = "F")

ds.age.female.signif <- top.ds.age.female |> 
  filter(adj.P.Val < 0.05)

ds.age.male.signif <- top.ds.age.male |> 
  filter(adj.P.Val < 0.05)

## Spline
X <- ns(pheno$age_years, df = 5)

design2 <- model.matrix(~group+group:X+most_recent_event+0, pheno)
colnames(design2) <- make.names(colnames(design2))

fit <- lmFit(eset, design2)

cont.dif <- makeContrasts(groupds.Female.X1 - groupnonds.Female.X1,
                          groupds.Female.X2 - groupnonds.Female.X2,
                          groupds.Female.X3 - groupnonds.Female.X3,
                          groupds.Female.X4 - groupnonds.Female.X4,
                          groupds.Female.X5 - groupnonds.Female.X5,
                          groupds.Female - groupnonds.Female,
                          groupds.Male.X1 - groupnonds.Male.X1,
                          groupds.Male.X2 - groupnonds.Male.X2,
                          groupds.Male.X3 - groupnonds.Male.X3,
                          groupds.Male.X4 - groupnonds.Male.X4,
                          groupds.Male.X5 - groupnonds.Male.X5,
                          groupds.Male - groupnonds.Male,
                          levels = design2) 

fit2 <- contrasts.fit(fit, cont.dif)
fit2 <- eBayes(fit2) 

top.ds.age.female.spline <- topTable(fit2, coef = 1:6, n = Inf, sort.by = "F")
top.ds.age.male.spline <- topTable(fit2, coef = 7:12, n = Inf, sort.by = "F")

ds.age.female.spline.signif <- top.ds.age.female.spline |> 
  filter(adj.P.Val < 0.05)

ds.age.male.spline.signif <- top.ds.age.male.spline |> 
  filter(adj.P.Val < 0.05)

## Female 
#signif.cytokine.female <- unique(c(rownames(ds.age.female.signif),
#                                rownames(ds.age.female.spline.signif)))

signif.cytokine.female <- rownames(ds.age.female.signif)

female.degs.expr <- exprs(eset[,eset$sex == 'Female']) |> 
  as.data.frame() |> 
  rownames_to_column('cytokine') |>  
  filter(cytokine %in% signif.cytokine.female) |> 
  column_to_rownames('cytokine') 

pheno.sorted.f <- pheno |> 
  filter(sex == 'Female') |> 
  arrange(age_years)

f.mat <- t(scale(t(female.degs.expr[,rownames(pheno.sorted.f)])))

# Best number clusters - Gap statistic
index = c("kl", "ch", "hartigan", "cindex", "db", "silhouette", "duda", "pseudot2", 
          "beale", "ratkowsky", "ball", "ptbiserial", "gap", "frey", "mcclain", 
          "gamma", "gplus", "tau", "dunn", "sdindex", "sdbw")

opt.n.cluster <- list()
for(i in seq_along(index)){
opt.n.cluster[[i]] <- NbClust(f.mat, min.nc = 2, max.nc = 10, index = index[i],
                         alphaBeale = 0.1, method = 'kmeans')$Best.nc[1]
}
names(opt.n.cluster) <- index

opt.clusters <- as.double(names(which.max(table(unlist(opt.n.cluster)))))

set.seed(42)
clLS.kmeans.female <- kmeans(f.mat, opt.clusters)

# plot heatmap with clusters 
column_ha = ComplexHeatmap::HeatmapAnnotation(age_years = pheno.sorted.f$age_years)

draw(Heatmap(f.mat, name = 'z-score', cluster_columns = F, 
        show_row_names = T, show_column_names = F,
        top_annotation = column_ha, row_names_gp = gpar(fontsize = 6),
        column_split = pheno.sorted.f$ds, row_split = clLS.kmeans.female$cluster,
        width = unit(10, 'cm'), height = unit(6, 'cm')),
     column_title = 'Cytokines - Female')

## Male
#signif.metab.male <- unique(c(rownames(ds.age.male.signif),
#                                rownames(ds.age.male.spline.signif)))

signif.cytokine.male <- unique(rownames(ds.age.male.signif))

male.degs.expr <- exprs(eset[,eset$sex == 'Male']) |> 
  as.data.frame() |> 
  rownames_to_column('cytokine') |>  
  filter(cytokine %in% signif.cytokine.male) |> 
  column_to_rownames('cytokine') 

pheno.sorted.m <- pheno |> 
  filter(sex == 'Male') |> 
  arrange(age_years)

m.mat <- t(scale(t(male.degs.expr[,rownames(pheno.sorted.m)])))

# Best number clusters - Gap statistic
index = c("kl", "ch", "hartigan", "cindex", "db", "silhouette", "duda", "pseudot2", 
          "beale", "ratkowsky", "ball", "ptbiserial", "gap", "frey", "mcclain", 
          "gamma", "gplus", "tau", "dunn", "sdindex", "sdbw")

opt.n.cluster <- list()
for(i in seq_along(index)){
opt.n.cluster[[i]] <- NbClust(m.mat, min.nc = 2, max.nc = 10, index = index[i],
                         alphaBeale = 0.1, method = 'kmeans')$Best.nc[1]
}
names(opt.n.cluster) <- index

opt.clusters <- as.double(names(which.max(table(unlist(opt.n.cluster)))))

clLS.kmeans.male <- kmeans(m.mat.imputed, 2)

# Plot heatmap with clusters
column_ha = ComplexHeatmap::HeatmapAnnotation(age_years = pheno.sorted.m$age_years)

draw(Heatmap(m.mat, name = 'z-score', cluster_columns = F, 
        show_row_names = T, show_column_names = F, 
        top_annotation = column_ha, row_names_gp = gpar(fontsize = 7),
        column_split = pheno.sorted.m$ds, 
        #row_split = clLS.kmeans.male$cluster,
        width = unit(10, 'cm'), height = unit(2, 'cm')), 
     column_title = 'Cytokines - Male')

## Over representation analysis
gene_set <- gmtPathways("../covid_single-cell/data/metabolomics/smpdb_collection_metabolic_transformed.gmt")

#metabolon_gene_set <- gene_set[grepl('METABOLON', names(gene_set))]

term2gene <- stack(gene_set) |>  
  dplyr::rename(term = ind, gene = values) %>% 
  relocate(term, gene)

clLS.metabid.male <- enframe(clLS.kmeans.male$cluster, 
                    name =  'PLOT_NAME', value = 'cluster') |>   
  left_join(rowData(metab.se) |> as.data.frame() |> 
              rownames_to_column('metabid') |> select(metabid, PLOT_NAME)) |> 
  select(metabid, cluster)
  
metab.cluster.list <- split(clLS.metabid.male$metabid, clLS.metabid.male$cluster)

ora.male <- compareCluster(metab.cluster.list, fun = 'enricher', 
                           TERM2GENE = term2gene, pvalueCutoff = Inf,
                           universe =  rownames(metab.counts))

ora.male.cluster.plot <- dotplot(ora.male, showCategory = 15, size = "Count", 
                                 label_format = 50, color = "pvalue", 
                    font.size = 10) +
  scale_fill_viridis_c(direction = -1)

#ggsave('results/metabolites/figures/dotplot_enrichment_metabolites_ds_nonds_age_male.pdf',
#       ora.male.cluster.plot, scale = 0.52)

# Trajectory
m.metab.cluster <- m.mat |> 
  as.data.frame() |> 
  rownames_to_column('metabid') |> 
  left_join(enframe(clLS.kmeans.male$cluster, 
                    name =  'metabid', value = 'cluster')) |>  
  pivot_longer(-c(metabid, cluster)) |> 
  left_join(pheno.sorted.m |> 
              rownames_to_column('name') |> 
              dplyr::select(name, age_years, ds)) |> 
  mutate(cluster = as.character(cluster))
  
p.m <- m.metab.cluster |> 
  ggplot(aes(x = age_years, y = value, colour = ds)) +
  geom_smooth(aes(group = ds), method = "loess", alpha = 0.3, linewidth = 1.5) +
  facet_wrap(~cluster) +
  scale_colour_manual(values = c("#F0F921FF", "#0D0887FF"), 
                      labels = c('DS', 'non-DS'),
                      name = "Group") +
  labs(title = 'Age-associated metabolites levels - Male', y = 'z-score',
       x = 'Age (years)')

#ggsave('results/metabolites/figures/regression_plot_clusters_male.pdf',
#       p.m, scale = 0.5)


## Overlap between males and females
male.metab.clusters <- enframe(clLS.kmeans.male$cluster, 
                               name =  'PLOT_NAME', value = 'cluster')

male.metab.clusters.list <- split(male.metab.clusters$PLOT_NAME, 
                                  male.metab.clusters$cluster)

female.metab.clusters <- enframe(clLS.kmeans.female$cluster, 
                                 name =  'PLOT_NAME', value = 'cluster')

female.metab.clusters.list <- split(female.metab.clusters$PLOT_NAME, 
                                    female.metab.clusters$cluster)




## Plot individual metabolites by age group
metab.counts.tidy <- metab.counts |> 
  as.data.frame() |> 
  rownames_to_column('metabid') |> 
  left_join(rowData(metab.se) |> as.data.frame() |> 
              rownames_to_column('metabid') |> select(metabid, PLOT_NAME, SUB_PATHWAY)) |> 
  select(-metabid) |> 
  pivot_longer(-c(PLOT_NAME,  SUB_PATHWAY), names_to = 'sampleid')  |> 
  left_join(pheno |> rownames_to_column('sampleid') |> select(sampleid, sex, ds, age_years)) |> 
  mutate(age_cat = case_when(age_years < 30 ~ '<30',
                             age_years > 30 ~ '>30')) |> 
  mutate(age_cat = factor(age_cat, levels = c('<30', '>30')))

metab.counts.tidy |> 
  filter(PLOT_NAME == "heme" )  |> 
  ggplot(aes(x = ds, y = value, fill = age_cat)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitterdodge(jitter.width = 0.2), shape = 21) + 
  facet_wrap(~sex)

heme.plot <- metab.counts.tidy |> 
  filter(PLOT_NAME == "heme" )  |> 
  ggplot(aes(x = age_years, y = value)) +
  geom_point(aes(fill = ds), shape = 21) +
  geom_smooth(aes(colour = ds), method='lm', alpha = 0.3, linewidth = 1.5) +
  #geom_smooth(aes(group = ds), method = "loess", alpha = 0.3, linewidth = 1.5) +
  facet_wrap(~sex) +
  ggtitle('Heme')

ggsave('results/metabolites/figures/scatterplot_heme_sex_ds.pdf',
       heme.plot, scale = 0.5)

sphingosine.plot <- metab.counts.tidy |> 
  filter(PLOT_NAME == "sphingosine 1-phosphate" )  |> 
  ggplot(aes(x = age_years, y = value)) +
  geom_point(aes(fill = ds), shape = 21) +
  geom_smooth(aes(colour = ds), method='lm', alpha = 0.3, linewidth = 1.5) +
  #geom_smooth(aes(group = ds), method = "loess", alpha = 0.3, linewidth = 1.5) +
  facet_wrap(~sex) +
  ggtitle('Sphingosine 1-phosphate')

ggsave('results/metabolites/figures/scatterplot_sphingosine_sex_ds.pdf',
       sphingosine.plot, scale = 0.5)

```

```{r Correlation - ABs (Spike) vs Cytokines}
ab.cytok <- ds.mae[['MSD.plasma']] |> 
  t() |> 
  as.data.frame() |> 
  rownames_to_column('sampleid') |> 
  right_join(sub.v2 |> select(sampleid, `SARS-CoV2 Spike`)) 

cor.ab.cytok <- ab.cytok |> 
  rstatix::cor_test(vars = contains('SARS'), method = 'spearman') |> 
  adjust_pvalue(p.col = 'p', method = 'BH') |> 
  arrange(p)

#write_tsv(cor.ab.cytok ,
#         'results/cytokines/spearman_correlation_cytokines_Spike_56patients_DS_vs_nonDS.tsv')
```


