---
title: "Down syndrome IJC - Flow cytometry analysis"
editor_options: 
  chunk_output_type: console
---

```{r Load libraries}
library(MultiAssayExperiment)
library(tidyverse)
library(ggfortify)
library(pvca)
library(limma)
library(ComplexHeatmap)
library(rstatix)
```

```{r Load files}
ds.mae <- readRDS('data/processed_multiassay_experiment/ds_ijc_multiassay_20240507.rds')

flow.se <- ds.mae[['Flow.cytometry']]

subset.patients <- read_tsv('results/antibodies/selected_patients_visit2_56.tsv')
```

```{r pvca function}
#https://github.com/dleelab/pvca

PVCA <- function(counts, meta, threshold, inter){

  counts.center <- t(apply(counts, 1, scale, center=TRUE, scale=FALSE))
  cor.counts <- cor(counts.center)
  dim(cor.counts)
  eigen.counts <- eigen(cor.counts)
  eigen.mat <- eigen.counts$vectors
  eigen.val <- eigen.counts$values
  n.eigen <- length(eigen.val)
  eigen.val.sum <- sum(eigen.val)
  percents.pcs <- eigen.val/eigen.val.sum
  meta <- as.data.frame(meta)

  all <- 0
  npc.in <- 0
  for(i in 1:n.eigen){
    all <- all + percents.pcs[i]
    npc.in <- npc.in + 1
    if(all > threshold){break}
  }
  if (npc.in < 3) {npc <- 3}

  pred.list <- colnames(meta)
  meta <- droplevels(meta)

  n.preds <- ncol(meta) + 1
  if(inter) {n.preds <- n.preds + choose(ncol(meta),2)}

  ran.pred.list <- c()
  for(i in 1:ncol(meta)){
    ran.pred.list <- c(ran.pred.list, paste0("(1|", pred.list[i],")"))
  }
  ##interactions
  if(inter){
    for(i in 1:(ncol(meta)-1)){
      for(j in (i+1):ncol(meta)){
        ran.pred.list <- c(ran.pred.list, paste0("(1|", pred.list[i], ":", pred.list[j], ")"))
        pred.list <- c(pred.list, paste0(pred.list[i], ":", pred.list[j]))
      }
    }
  }
  formula <- paste(ran.pred.list, collapse = " + ")
  formula <- paste("pc", formula, sep=" ~ ")
  ran.var.mat <- NULL
  for(i in 1:npc.in){
    dat <- cbind(eigen.mat[,i],meta)
    colnames(dat) <- c("pc",colnames(meta))
    Rm1ML <- lme4::lmer(formula, dat, REML = TRUE, verbose = FALSE, na.action = na.omit)
    var.vec <- unlist(VarCorr(Rm1ML))
    ran.var.mat <- rbind(ran.var.mat, c(var.vec[pred.list], resid = sigma(Rm1ML)^2))
  }
  ran.var.mat.std <- ran.var.mat/rowSums(ran.var.mat)
  wgt.vec <- eigen.val/eigen.val.sum
  prop.var <- colSums(ran.var.mat.std*wgt.vec[1:npc.in])
  std.prop.var <- prop.var/sum(prop.var)
  std.prop.var
}

PlotPVCA <- function(pvca.res, title){
  plot.dat <- data.frame(eff=names(pvca.res), prop=pvca.res)
  p <- ggplot2::ggplot(plot.dat, aes(x=eff, y=prop))
  p <- p + ggplot2::ggtitle(title)
  p <- p + ggplot2::geom_bar(stat="identity", fill="steelblue", colour="steelblue")
  p <- p + ggplot2::geom_text(aes(label=round(prop,3), y=prop+0.04), size=4)
  p <- p + ggplot2::scale_x_discrete(limits=names(pvca.res))
  p <- p + ggplot2::scale_y_continuous(limits = c(0,1))
  p <- p + ggplot2::labs(x= "Effects", y= "Weighted average proportion variance")
  p <- p + ggplot2::theme_bw()
  p <- p + ggplot2::theme(plot.background = element_blank() ,panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank() ,panel.border = element_blank(), panel.background = element_blank())
  p <- p + ggplot2::theme(axis.line = element_line(color = 'black'))
  p <- p + ggplot2::theme(axis.title.x = element_text(size = 15, vjust=-0.5))
  p <- p + ggplot2::theme(axis.title.y = element_text(size = 15, vjust= 1.0))
  p <- p + ggplot2::theme(axis.text = element_text(size = 12))
  p <- p + ggplot2::theme(axis.text.x = element_text(angle = 90, vjust= 0.5, hjust=1))
  p
}
```

```{r EDA}
se.flow <- ds.ma[['Flow.cytometry']]

flow.df <- assay(se.flow, 'Unstimulated') %>% 
  as.data.frame() %>% 
  filter(rowMeans(. < 0, na.rm = T) < 0.1) %>%  # remove flow gates with more 10% negative values (compensation problem)
  log1p() %>% 
  filter(rowMeans(is.na(.)) < 1/3) %>% # remove flow gates with more 1/3 NA
  t() %>% 
  as.data.frame() %>%  
  mutate_all(~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x))

## PCA
autoplot(prcomp(log1p(flow.df), scale. = T), 
         data = as.data.frame(colData(se.flow)), fill = 'DS', shape = 21, size = 3,
         names = T, alpha = 0.8) +
  scale_fill_manual(values = c("#0D0887FF", "#F0F921FF"), name = 'Group',
                    labels = c('HC', 'DS')) +
  ggtitle('PCA - Flow cytometry')+
  theme_bw()

### PVCA ----
metadata <- colData(se.flow) %>% 
  as.data.frame() %>% 
  rownames_to_column('sampleid') %>% 
  mutate(BMI = ifelse(BMI < 5, NA, BMI)) %>% 
  mutate(bmi_category = case_when(BMI < 18.5 ~ 'underweight',
                                  BMI >= 18.5 & BMI < 25 ~ 'healthy',
                                  BMI >= 25 & BMI < 30 ~ 'overweight',
                                  BMI >= 30 ~ 'obesity',
                                  TRUE ~ NA_character_)) %>% 
  mutate(age_category = case_when(Age < 30 ~ 'under_30',
                                  TRUE ~ 'over_30')) %>% 
  column_to_rownames('sampleid') %>% 
  select(DS, age_category, bmi_category, Sex)

pvca <- PVCA(t(flow.df), meta = metadata, threshold = 0.1, inter = F)
pvca.plot <- PlotPVCA(pvca, title = 'PVCA - Flow cytometry')

eset <- ExpressionSet(assayData = t(flow.df)[,rownames(metadata)], 
                      phenoData = AnnotatedDataFrame(metadata))

batch.factors <- c('DS', 'age_category', 'bmi_category', 'Sex')

pvca <- pvcaBatchAssess(eset, batch.factors = batch.factors, threshold = 0.1)

df <- data.frame("Prop_var" = pvca$dat[1,], "condition" = pvca$label) %>%
          arrange(desc(Prop_var))

pvca.flow <- ggplot(df, aes(x = reorder(condition,Prop_var), 
                                   y = Prop_var)) +
    geom_bar(stat = "identity") +
    labs(x = "Condition",
         y = "Proportion of variance explained") +
    theme_bw() +
    coord_flip()

#ggsave('results/flow_cytometry/PVCA_flow.pdf', pvca.flow,
#       device = 'pdf', scale = 0.4)

### Linear regression DS vs HC
flow.df <- assay(se.flow, 'Unstimulated') %>% 
  as.data.frame() %>% 
  filter(rowMeans(. < 0, na.rm = T) < 0.1) %>%  # remove flow gates with more 10% negative values (compensation problem)
  log1p() %>% 
  filter(rowMeans(is.na(.)) < 1/3) %>% # remove flow gates with more 1/3 NA
  as.matrix()

designMat <- model.matrix(~ DS, data = metadata)

fit1 <- lmFit(flow.df[,rownames(metadata)], design = designMat)
fit2 <- eBayes(fit1)
top.ds <- topTable(fit2, coef=2, n = Inf, sort.by="none") %>% 
  arrange(adj.P.Val) %>% 
  rownames_to_column('feature')

summary(decideTests(fit2))

write_tsv(top.ds, 'results/flow_cytometry/limma_DS_vs_HC_flow.tsv')

top.features <- top.ds %>%
  filter(adj.P.Val < 0.05, abs(logFC) > 1) %>% 
  select(feature) %>% 
  deframe()

ds.group <- c("#0D0887FF", "#F0F921FF")
names(ds.group) <- c('no', 'yes')

annotCol = list(DS = ds.group)

pheatmap::pheatmap(flow.df[top.features,], scale = 'row',
                   color = colorRampPalette(c('darkblue', 'blue', 'white', 
                                              'red', 'darkred'))(100),
                   show_colnames = F, annotation_col = metadata,
                   annotation_colors = annotCol)

```

```{r Linear regression - DS}
flow.df <- assay(flow.se, 'Unstimulated') %>% 
  as.data.frame() %>%  
  select(all_of(subset.patients$sampleid))  %>% 
  filter(rowMeans(. < 0, na.rm = T) < 0.1) %>%  # remove flow gates with more 10% negative values (compensation problem)
  #log1p() %>% 
  filter(rowMeans(is.na(.)) < 1/3) %>%  # remove flow gates with more 1/3 NA
  as.matrix()

pheno <- subset.patients |> 
  column_to_rownames('sampleid') |> 
  mutate(most_recent_event = abs(most_recent_event))

design <- model.matrix(~ ds + age_years + sex + most_recent_event, data = pheno)

fit <- lmFit(log1p(flow.df), design = design)
fit <- eBayes(fit)

summary(decideTests(fit))

out <- topTable(fit, coef = 'dsyes', sort.by = 'p', n = Inf) |> 
  rownames_to_column('flow_feature')

#write_tsv(out, 'results/flow_cytometry/linear_regression_DS_56patients.tsv')
# Heatmap 
signif.flow <- out |> 
  as.data.frame() |> 
  filter(adj.P.Val < 0.05) |> 
  select(flow_feature) |> 
  deframe()

signif.flow.df <- t(scale(t(log1p(flow.df)[signif.flow,])))

ds.vector <- ifelse(pheno$ds == 'no', 'non-DS', 'DS')

ha = HeatmapAnnotation(Group = ds.vector, 
                       col = list(Group = c("DS" = "yellow", "non-DS" = "darkblue")))

Heatmap(signif.flow.df, name = 'z-score', show_column_names = F, 
        top_annotation = ha, column_split = ds.vector, row_split = 2,
        width = unit(6, "cm"), height = unit(25, "cm"), row_names_gp = gpar(fontsize = 4))


## Spearman correlation
## Only significant metabolites
flow.antibody.df <- t(flow.df) |> 
  as.data.frame() |> 
  rownames_to_column('sampleid') |> 
  left_join(subset.patients |> select('sampleid', 'SARS-CoV2 Spike')) |> 
  select(all_of(c('sampleid', 'SARS-CoV2 Spike', signif.flow)))

cor_flow_antibody <- flow.antibody.df |> 
  cor_test(vars = 'SARS-CoV2 Spike', method = 'spearman') |> 
  adjust_pvalue(p.col = 'p', method = 'BH') |> 
  arrange(p)

#write_tsv(cor_flow_antibody, 
#          'results/flow_cytometry/spearman_correl_SpikeABs_Flow_56patients.tsv')

signif.cor.flow.ab <- cor_flow_antibody |> 
  filter(p <= 0.05) |> 
  select(var2) |> 
  deframe()

spike.titer <- subset.patients |> 
  mutate(`Log10 SARS-CoV2 Spike` = log10(`SARS-CoV2 Spike`)) |> 
  arrange(`SARS-CoV2 Spike`)

ds.vector <- ifelse(spike.titer$ds == 'no', 'non-DS', 'DS')

col_fun = circlize::colorRamp2(seq(4, 6.5, length = 100), 
                               viridis::inferno(100, direction = -1))

ha = HeatmapAnnotation(Group = ds.vector, 
                       `SARS-CoV2 Spike` = spike.titer$`Log10 SARS-CoV2 Spike`,
                       col = list(Group = c("DS" = "yellow", "non-DS" = "darkblue"),
                                  `SARS-CoV2 Spike` = col_fun))

# select correlated features and sampleids following the sorted titer df
signif.flow.df <- t(scale(t(log1p(flow.df)[signif.cor.flow.ab, 
                                           spike.titer$sampleid])))

draw(Heatmap(signif.flow.df, name = 'z-score', show_column_names = F, 
        top_annotation = ha, row_split = 2, cluster_columns = F, 
        row_names_gp = gpar(fontsize = 8), width = unit(8, 'cm'), height = unit(7, 'cm')), 
     heatmap_legend_side = 'left',
     annotation_legend_side = "bottom")

# ALL flow features
flow.antibody.df <- t(flow.df) |> 
  as.data.frame() |> 
  rownames_to_column('sampleid') |> 
  left_join(subset.patients |> select('sampleid', 'SARS-CoV2 Spike')) 

cor_flow_antibody <- flow.antibody.df |> 
  cor_test(vars = 'SARS-CoV2 Spike', method = 'spearman') |> 
  adjust_pvalue(p.col = 'p', method = 'BH') |> 
  arrange(p)

write_tsv(cor_flow_antibody, 
          'results/flow_cytometry/spearman_correl_ALL_flow_features_vs_Spike_56patients.tsv')

signif.cor.flow.ab <- cor_flow_antibody |> 
  filter(p <= 0.05) |> 
  select(var2) |> 
  deframe()

spike.titer <- subset.patients |> 
  mutate(`Log10 SARS-CoV2 Spike` = log10(`SARS-CoV2 Spike`)) |> 
  arrange(`SARS-CoV2 Spike`)

ds.vector <- ifelse(spike.titer$ds == 'no', 'non-DS', 'DS')

col_fun = circlize::colorRamp2(seq(4, 6.5, length = 100), 
                               viridis::inferno(100, direction = -1))

ha = HeatmapAnnotation(Group = ds.vector, 
                       `SARS-CoV2 Spike` = spike.titer$`Log10 SARS-CoV2 Spike`,
                       col = list(Group = c("DS" = "yellow", "non-DS" = "darkblue"),
                                  `SARS-CoV2 Spike` = col_fun))

# select correlated features and sampleids following the sorted titer df
signif.flow.df <- t(scale(t(log1p(flow.df)[signif.cor.flow.ab, 
                                           spike.titer$sampleid])))

draw(Heatmap(signif.flow.df, name = 'z-score', show_column_names = F, 
        top_annotation = ha, row_split = 2, cluster_columns = F, 
        row_names_gp = gpar(fontsize = 8), width = unit(8, 'cm'), height = unit(13, 'cm')), 
     heatmap_legend_side = 'left',
     annotation_legend_side = "bottom")

## Intersection
signif.cor.flow.ab <- cor_flow_antibody |> 
  filter(p <= 0.05)  

intersec <- out |> 
  as.data.frame() |> 
  filter(adj.P.Val < 0.05) |> 
  inner_join(signif.cor.flow.ab, by = c('flow_feature' = 'var2'))

write_tsv(intersec, 
          'results/flow_cytometry/intersection_linear_regression_DS_vs_non-DS_spearman_correlation.tsv')

```

```{r Linear Model - age}
library(splines)
library(NbClust)
library(cluster)
library(ComplexHeatmap)
library(fgsea)
library(clusterProfiler)

## Using limma
flow.df <- assay(flow.se, 'Unstimulated') %>% 
  as.data.frame() %>%  
  filter(rowMeans(. < 0, na.rm = T) < 0.1) %>%  # remove flow gates with more 10% negative values (compensation problem)
  filter(rowMeans(is.na(.)) < 1/3) %>%  # remove flow gates with more 1/3 NA
  as.matrix()

pheno <- colData(flow.se) %>% 
  as.data.frame() %>% 
  rownames_to_column('sampleid') %>% 
  mutate(patientid = sub('_.*', '', sampleid)) %>% 
  left_join(colData(ds.mae) %>% 
              as.data.frame() %>% 
              rownames_to_column('patientid')) %>% 
  dplyr::select(sampleid, patientid, ds, age_years, weight_kg, 
                height_meter, sex, most_recent_event, number_events, X1st.infection.date) |>  
  mutate(height_meter = ifelse(height_meter > 100, height_meter/100, height_meter)) %>% 
  mutate(bmi =  weight_kg/height_meter^2) %>% 
  mutate(bmi = ifelse(bmi == 0, NA, bmi)) %>% 
  mutate(bmi = ifelse(bmi == Inf, NA, bmi)) %>% 
  mutate(most_recent_event = abs(most_recent_event)) |> 
  mutate(most_recent_event = ifelse(is.na(most_recent_event), 750, most_recent_event)) |>
  mutate(infection = ifelse(is.na(X1st.infection.date), 'no', 'yes')) |> 
  column_to_rownames('sampleid') |> 
  mutate(ds = ifelse(ds == 'yes', 'ds', 'nonds')) |> 
  mutate(group = paste(ds, sex, sep = '.'))

eset <- ExpressionSet(assayData = log1p(flow.df),
                      phenoData = AnnotatedDataFrame(pheno))

## Linear
design1 <- model.matrix(~group+group:age_years+most_recent_event+0, pheno)
colnames(design1) <- make.names(colnames(design1))

fit <- lmFit(eset, design1)

cont.dif <- makeContrasts(groupds.Female.age_years - groupnonds.Female.age_years,
                          groupds.Female - groupnonds.Female,
                          groupds.Male.age_years - groupnonds.Male.age_years,
                          groupds.Male - groupnonds.Male,
                          levels = design1) 

fit2 <- contrasts.fit(fit, cont.dif)
fit2 <- eBayes(fit2) 

top.ds.age.female <- topTable(fit2, coef = 1:2, n = Inf, sort.by = "F")
top.ds.age.male <- topTable(fit2, coef = 3:4, n = Inf, sort.by = "F")

ds.age.female.signif <- top.ds.age.female |> 
  filter(adj.P.Val < 0.05)

ds.age.male.signif <- top.ds.age.male |> 
  filter(adj.P.Val < 0.05)

## Spline
X <- ns(pheno$age_years, df = 5)

design2 <- model.matrix(~group+group:X+most_recent_event+0, pheno)
colnames(design2) <- make.names(colnames(design2))

fit <- lmFit(eset, design2)

cont.dif <- makeContrasts(groupds.Female.X1 - groupnonds.Female.X1,
                          groupds.Female.X2 - groupnonds.Female.X2,
                          groupds.Female.X3 - groupnonds.Female.X3,
                          groupds.Female.X4 - groupnonds.Female.X4,
                          groupds.Female.X5 - groupnonds.Female.X5,
                          groupds.Female - groupnonds.Female,
                          groupds.Male.X1 - groupnonds.Male.X1,
                          groupds.Male.X2 - groupnonds.Male.X2,
                          groupds.Male.X3 - groupnonds.Male.X3,
                          groupds.Male.X4 - groupnonds.Male.X4,
                          groupds.Male.X5 - groupnonds.Male.X5,
                          groupds.Male - groupnonds.Male,
                          levels = design2) 

fit2 <- contrasts.fit(fit, cont.dif)
fit2 <- eBayes(fit2) 

top.ds.age.female.spline <- topTable(fit2, coef = 1:6, n = Inf, sort.by = "F")
top.ds.age.male.spline <- topTable(fit2, coef = 7:12, n = Inf, sort.by = "F")

ds.age.female.spline.signif <- top.ds.age.female.spline |> 
  filter(adj.P.Val < 0.05)

ds.age.male.spline.signif <- top.ds.age.male.spline |> 
  filter(adj.P.Val < 0.05)

#exprs(eset) |> 
#  as.data.frame() |> 
#  rownames_to_column('metabid') |> 
#  pivot_longer(-metabid, names_to = 'sampleid') |> 
#  left_join(pheno |> rownames_to_column('sampleid')) |> 
#  filter(metabid == 409, sex == 'Male') |> 
#  arrange(age_years) |> 
#  ggplot(aes(x = age_years, y = value)) +
#  geom_point(aes(fill = ds), shape = 21) +
#  geom_smooth(aes(group = ds, colour = ds), method='lm', formula= y~x)

## Female 
signif.flow.female <- unique(c(rownames(ds.age.female.signif),
                               rownames(ds.age.female.spline.signif)))

female.degs.expr <- exprs(eset[,eset$sex == 'Female']) |> 
  as.data.frame() |> 
  rownames_to_column('feature') |> 
  filter(feature %in% signif.flow.female) |> 
  column_to_rownames('feature')

pheno.sorted.f <- pheno |> 
  filter(sex == 'Female') |> 
  arrange(age_years)

f.mat <- t(scale(t(female.degs.expr[,rownames(pheno.sorted.f)])))

# Best number clusters - Gap statistic
index = c("kl", "ch", "hartigan", "cindex", "db", "silhouette", "duda", "pseudot2", 
          "beale", "ratkowsky", "ball", "ptbiserial", "gap", "frey", "mcclain", 
          "gamma", "gplus", "tau", "dunn", "sdindex", "sdbw")

opt.n.cluster <- list()
for(i in seq_along(index)){
opt.n.cluster[[i]] <- NbClust(f.mat, min.nc = 2, max.nc = 10, index = index[i],
                         alphaBeale = 0.1, method = 'kmeans')$Best.nc[1]
}
names(opt.n.cluster) <- index

f.mat.imputed <- missMethods::impute_median(f.mat, type = 'rowise')
fit.kmeans <- clusGap(f.mat.imputed, kmeans, K.max = 10, iter.max = 20)
nC.kmeans <- maxSE(fit.kmeans$Tab[, "gap"], 
                   fit.kmeans$Tab[, "SE.sim"], 
                   method = "Tibs2001SEmax")

# plot gap
plot(fit.kmeans, main = "Optimal clusters number")
abline(v = nC.kmeans, col = "blue")

set.seed(42)
clLS.kmeans.female <- kmeans(f.mat.imputed, 2)

# plot heatmap with clusters 
column_ha = ComplexHeatmap::HeatmapAnnotation(age_years = pheno.sorted.f$age_years)

#row.annot <- f.mat |> 
#  as.data.frame() |> 
#  rownames_to_column('PLOT_NAME') |> 
#  left_join(rowData(metab.se) |> as.data.frame() |> 
#               select(PLOT_NAME, SUPER_PATHWAY)) |> 
#  select(PLOT_NAME, SUPER_PATHWAY) |> 
#  deframe()

#class.color <- RColorBrewer::brewer.pal(9, 'Paired')
#names(class.color) <- unique(row.annot)

#row_ha = rowAnnotation(Class = row.annot, 
#                       col = list(Class = class.color))

draw(Heatmap(f.mat, name = 'z-score', cluster_columns = F, 
        show_row_names = T, show_column_names = F, 
        #right_annotation = row_ha,
        top_annotation = column_ha, row_names_gp = gpar(fontsize = 2),
        column_split = pheno.sorted.f$ds, 
        row_split = clLS.kmeans.female$cluster,
        width = unit(10, 'cm'), height = unit(25, 'cm')),
     column_title = '404 flow features - Female')

# Trajectory
f.metab.cluster <- f.mat |> 
  as.data.frame() |> 
  rownames_to_column('feature') |> 
  left_join(enframe(clLS.kmeans.female$cluster, 
                    name =  'feature', value = 'cluster')) |>  
  pivot_longer(-c(feature, cluster)) |> 
  left_join(pheno.sorted.f |> 
              rownames_to_column('name') |> 
              dplyr::select(name, age_years, ds)) |> 
  mutate(cluster = as.character(cluster))
  
p.f <- f.metab.cluster |> 
  ggplot(aes(x = age_years, y = value, colour = ds)) +
  geom_smooth(aes(group = ds), method = "loess", alpha = 0.3, linewidth = 1.5) +
  facet_wrap(~cluster) +
  scale_colour_manual(values = c("#F0F921FF", "#0D0887FF"), 
                      labels = c('DS', 'non-DS'),
                      name = "Group") +
  labs(title = 'Age-associated flow features - Female', y = 'z-score',
       x = 'Age (years)')

ggsave('results/flow_cytometry/regression_plot_clusters_female.pdf',
       p.f, scale = 0.5)

## Male
signif.metab.male <- unique(c(rownames(ds.age.male.signif),
                                rownames(ds.age.male.spline.signif)))

male.degs.expr <- exprs(eset[,eset$sex == 'Male']) |> 
  as.data.frame() |> 
  rownames_to_column('feature') |>   
  filter(feature %in% signif.metab.male) |> 
  column_to_rownames('feature')

pheno.sorted.m <- pheno |> 
  filter(sex == 'Male') |> 
  arrange(age_years)

m.mat <- t(scale(t(male.degs.expr[,rownames(pheno.sorted.m)])))

# Best number clusters - Gap statistic
index = c("kl", "ch", "hartigan", "cindex", "db", "silhouette", "duda", "pseudot2", 
          "beale", "ratkowsky", "ball", "ptbiserial", "gap", "frey", "mcclain", 
          "gamma", "gplus", "tau", "dunn", "sdindex", "sdbw")

opt.n.cluster <- list()
for(i in seq_along(index)){
opt.n.cluster[[i]] <- NbClust(m.mat, min.nc = 2, max.nc = 10, index = index[i],
                         alphaBeale = 0.1, method = 'kmeans')$Best.nc[1]
}
names(opt.n.cluster) <- index

m.mat.imputed <- missMethods::impute_median(m.mat, type = 'rowise')
fit.kmeans <- clusGap(m.mat.imputed, kmeans, K.max = 10, iter.max = 50)
nC.kmeans <- maxSE(fit.kmeans$Tab[, "gap"], 
                   fit.kmeans$Tab[, "SE.sim"],
                   method = 'Tibs2001SEmax')

# plot gap
plot(fit.kmeans, main = "Optimal clusters number")
abline(v = nC.kmeans, col = "blue")

set.seed(42)
clLS.kmeans.male <- kmeans(m.mat.imputed, 2)

# Plot heatmap with clusters
column_ha = ComplexHeatmap::HeatmapAnnotation(age_years = pheno.sorted.m$age_years)

#row.annot <- m.mat |> 
#  as.data.frame() |> 
#  rownames_to_column('PLOT_NAME') |> 
#  left_join(rowData(metab.se) |> as.data.frame() |> 
#               select(PLOT_NAME, SUPER_PATHWAY)) |> 
#  select(PLOT_NAME, SUPER_PATHWAY) |> 
#  deframe()

#class.color <- RColorBrewer::brewer.pal(9, 'Paired')
#names(class.color) <- unique(row.annot)

#row_ha = rowAnnotation(Class = row.annot, 
#                       col = list(Class = class.color))

draw(Heatmap(m.mat, name = 'z-score', cluster_columns = F, 
        show_row_names = T, show_column_names = F, 
        #right_annotation = row_ha,
        top_annotation = column_ha, row_names_gp = gpar(fontsize = 3),
        column_split = pheno.sorted.m$ds, row_split = clLS.kmeans.male$cluster,
        width = unit(10, 'cm'), height = unit(25, 'cm')), 
     column_title = '284 flow features - Male')

# Trajectory
m.flow.cluster <- m.mat |> 
  as.data.frame() |> 
  rownames_to_column('feature') |> 
  left_join(enframe(clLS.kmeans.male$cluster, 
                    name =  'feature', value = 'cluster')) |>  
  pivot_longer(-c(feature, cluster)) |> 
  left_join(pheno.sorted.m |> 
              rownames_to_column('name') |> 
              dplyr::select(name, age_years, ds)) |> 
  mutate(cluster = as.character(cluster))
  
p.m <- m.flow.cluster |> 
  ggplot(aes(x = age_years, y = value, colour = ds)) +
  geom_smooth(aes(group = ds), method = "loess", alpha = 0.3, linewidth = 1.5) +
  facet_wrap(~cluster) +
  scale_colour_manual(values = c("#F0F921FF", "#0D0887FF"), 
                      labels = c('DS', 'non-DS'),
                      name = "Group") +
  labs(title = 'Age-associated flow cytometry features - Male', y = 'z-score',
       x = 'Age (years)')

#ggsave('results/flow_cytometry/regression_plot_clusters_male.pdf',
#       p.m, scale = 0.5)


## Overlap between males and females
male.metab.clusters <- enframe(clLS.kmeans.male$cluster, 
                               name =  'PLOT_NAME', value = 'cluster')

male.metab.clusters.list <- split(male.metab.clusters$PLOT_NAME, 
                                  male.metab.clusters$cluster)

female.metab.clusters <- enframe(clLS.kmeans.female$cluster, 
                                 name =  'PLOT_NAME', value = 'cluster')

female.metab.clusters.list <- split(female.metab.clusters$PLOT_NAME, 
                                    female.metab.clusters$cluster)

```
