---
title: "MCIA"
editor_options: 
  chunk_output_type: console
---

```{r Load libraries}
library(omicade4)
library(tidyverse)
library(rstatix)
```

```{r load files}
ds.mae <- readRDS('data/processed_multiassay_experiment/ds_ijc_multiassay_20240507.rds')

subset.patients <- read_tsv('results/antibodies/selected_patients_visit2_56.tsv')
```

```{r data pre-processing}
# antibodies
abs.df <- ds.mae[['Antibodies']] |> 
  as.data.frame() |> 
  select(all_of(subset.patients$sampleid)) 

scaled.ab.df <- t(scale(t(log1p(abs.df))))
t.ab.df <- log1p(abs.df)

# cytokines
cytok.df <- ds.mae[['MSD.plasma']] |> 
  t() |> 
  as.data.frame() |> 
  rownames_to_column('sampleid') |> 
  filter(sampleid %in% subset.patients$sampleid) |> 
  column_to_rownames('sampleid')

scaled.cytok.df <- t(scale(log1p(cytok.df)))[,subset.patients$sampleid]
t.cytok.df <- t(log1p(cytok.df))[,subset.patients$sampleid]

# flow
flow.se <- ds.mae[['Flow.cytometry']]
flow.df <- assay(flow.se, 'Unstimulated') %>% 
  as.data.frame() |> 
  select(all_of(subset.patients$sampleid)) %>% 
  filter(rowMeans(. < 0, na.rm = T) < 0.1) %>%  # remove flow gates with more 10% negative values (compensation problem)
  mutate_all(~ifelse(.x < 0, NA, .x)) %>%   # replace negative values by NA
  filter(rowMeans(is.na(.)) < 1/3) %>% # remove flow gates with more 1/3 NA
  t() %>% 
  as.data.frame() %>%  
  mutate_all(~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x)) 

scaled.flow.df <- t(scale(log1p(flow.df)))[,subset.patients$sampleid]
t.flow.df <- t(log1p(flow.df))[,subset.patients$sampleid]
  
# metabolites
metab.se <- ds.mae[['Metabolites']] 

metab.df <- assay(metab.se) %>% 
  as.data.frame() |> 
  select(all_of(subset.patients$sampleid)) %>% 
  filter(rowMeans(is.na(.)) < 1/3) |>  # remove metabs with more 1/3 NA
  t() %>% 
  as.data.frame() %>%  
  mutate_all(~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x))

scaled.metab.df <- t(scale(metab.df))[,subset.patients$sampleid]
t.metab.df <- t(metab.df)[,subset.patients$sampleid]

# rna-seq
rnaseq.df <- read_tsv('results/rnaseq/gsva_All_Hallmark_BTM_pathways_56patients.tsv') |> 
  column_to_rownames('ID') |> 
  t() |> 
  as.data.frame() |> 
  rownames_to_column('sampleid') |> 
  mutate(sampleid = paste0(sub('.*_', '', sampleid), '_V2')) |> 
  column_to_rownames('sampleid') |> 
  t()

scaled.rnaseq.df <- t(scale(t(rnaseq.df)))
  
```

```{r MCIA}
intr.list <- list(metabolites = scaled.metab.df,
                  cytokines = scaled.cytok.df,
                  flow.cytometry = scaled.flow.df,
                  rna.seq = scaled.rnaseq.df,
                  antibodies = scaled.ab.df[-1,])

mcia.ds <- mcia(intr.list, cia.nf = 20)

## Inspect synvar
synvar.ms <- mcia.ds$mcoa$SynVar %>% 
  rownames_to_column('sampleid') |> 
  left_join(subset.patients %>% 
              mutate(sampleid = paste0('X', sampleid)) |> 
              select(sampleid, ds, `SARS-CoV2 Spike`)) 

cor.synvar.spike <- synvar.ms %>%
  cor_test(vars = 'SARS-CoV2 Spike',
           vars2 = starts_with('SynVar'), method = 'spearman') %>% 
  adjust_pvalue(p.col = 'p', method = 'BH') |> 
  arrange(p)

design <- model.matrix(~ ds + age_years + sex + most_recent_event, 
                       data = subset.patients |> column_to_rownames('sampleid'))

synvar.ms.df <- synvar.ms |> 
  mutate(sampleid = sub('X', '', sampleid)) |> 
  column_to_rownames('sampleid') |> 
  select(-c(ds, `SARS-CoV2 Spike`))

fit <- lmFit(t(synvar.ms.df), design = design)
fit <- eBayes(fit)

summary(decideTests(fit))

out <- topTable(fit, coef = 'dsyes', sort.by = 'p', n = Inf)

## plot
ds.vector <- ifelse(subset.patients$ds == 'no', 'non-DS', 'DS')

plot(mcia.ds, sample.lab = F, df.color = 1:5, phenovec = ds.vector, axes= c(1,7),
     c('yellow3','darkblue')[factor(ds.vector)], sample.legend = F, gene.nlab = 1)


## Correl
data <- t(rbind(scaled.metab.df, scaled.cytok.df, scaled.flow.df, scaled.rnaseq.df))

synvar.df <- mcia.ds$mcoa$SynVar |> 
  select(SynVar2) |> 
  rownames_to_column('id') |> 
  mutate(id = sub('X', '', id)) |> 
  column_to_rownames('id')

cor_synvar_features <- merge(synvar.df, data, by = 'row.names') |> 
  cor_test(vars = 'SynVar2', method = 'spearman') |> 
  adjust_pvalue(p.col = 'p', method = 'BH')

cor_synvar_features.out <- cor_synvar_features |>
  left_join(as.data.frame(rowData(metab.se)) |> 
              rownames_to_column('var2') |> 
              select(var2, PLOT_NAME)) |> 
  mutate(dataset = case_when(var2 %in% rownames(scaled.metab.df) ~ 'metabolites',
                             var2 %in% rownames(scaled.cytok.df) ~ 'cytokines',
                             var2 %in% rownames(scaled.flow.df) ~ 'flow.cytometry',
                             var2 %in% rownames(scaled.rnaseq.df) ~ 'rna.seq')) |> 
  mutate(var2 = ifelse(is.na(PLOT_NAME), var2, PLOT_NAME)) |> 
  select(-PLOT_NAME) |> 
  relocate(var1, var2, dataset) |> 
  arrange(p)

write_tsv(cor_synvar_features.out, 
          'results/mcia_integration/spearman_correlation_SynVar2_features.tsv')
  

pos <- selectVar(mcia.covid, a2.lim = c(0.5, Inf))
neg <- selectVar(mcia.covid, a2.lim = c(-Inf, -0.5))

#write_tsv(pos, 'results/figures_old/y23wk08/positive_mcia_cytokines_metabolites.tsv')
#write_tsv(neg, 'results/figures_old/y23wk08/negative_mcia_cytokines_metabolites.tsv')

plotVar(mcia.covid, axes= c(1,2),  
        var = c('quinolinate_nicotinate_and_nicotinamide_metabolism',
                'il_10_plasma', 'il_1b_plasma', 'il_6_plasma', 'il_8_human_plasma',
                'il_22_plasma', 'indolepropionate_tryptophan_metabolism', 
                'serotonin_tryptophan_metabolism', 'mcp_3_plasma'),
        sepID.data=5, var.lab = T)
```

```{r Feature selection}
# RNA
rnaseq.cor <- read_tsv('results/rnaseq/spearman_correlation_gsva_All_Hallmark_BTM_pathways_spike_56patients.tsv') |> 
  filter(p < 0.05) |> 
  mutate(class = 'rna.seq') |> 
  relocate(class)

rnaseq.cor.df <- rnaseq.df[rnaseq.cor$var2,subset.patients$sampleid]

# Metabolites
metab.cor <- read_tsv('results/metabolites/spearman_correlation_All_metabolites_vs_Spike_56_samples.tsv') |> 
  filter(p < 0.05) |> 
  mutate(class = 'metabolites') |> 
  relocate(class)

metab.cor.df <- t.metab.df[as.character(metab.cor$var2),]

# Flow
flow.cor <- read_tsv('results/flow_cytometry/spearman_correl_ALL_flow_features_vs_Spike_56patients.tsv') |> 
  filter(p < 0.05) |> 
  mutate(class = 'flow') |> 
  relocate(class)

flow.cor.df <- t.flow.df[flow.cor$var2,]

# Combine correlation df
feature.cor <- rnaseq.cor |> 
  bind_rows(metab.cor |> 
              mutate(var2 = as.character(var2)) |> 
              left_join(as.data.frame(rowData(metab.se)) |> 
                          rownames_to_column('var2') |> 
                          select(var2, PLOT_NAME)) |> 
              mutate(var2 = PLOT_NAME) |> 
              select(-PLOT_NAME)) |> 
  bind_rows(flow.cor)

write_tsv(feature.cor, 
          'results/mcia_integration/correlated_features_for_feature_selection.tsv')

# Combine datasets
rna.metab.flow.df <- rnaseq.cor.df |> 
  as.data.frame() |> 
  bind_rows(as.data.frame(metab.cor.df)) |> 
  bind_rows(as.data.frame(flow.cor.df))

### Feature selection
# Independent variables (data frame of cytokines as columns and samples as rows)
#X <- df.tetr.scaled[, signif.percentage.cytok]
X <- t(rna.metab.flow.df)

# Dependent variable (outcome/groups)
#Y <- df.tetr.scaled[,1]
Y <- subset.patients |> 
  column_to_rownames('sampleid') |> 
  mutate(log10_sarscov2_spike = log10(`SARS-CoV2 Spike`)) |> 
  select(log10_sarscov2_spike) |> 
  as.matrix()
  
# bionomial glmnet
fitFull <- glmnet(x = X,
                  y = Y,
                  family = "gaussian",
                  alpha = 1)

set.seed(seed = 42)
fit2Full <- cv.glmnet(x = X,
                      y = Y,
                      family = "gaussian",
                      lambda = fitFull$lambda,
                      type.measure = "mse",
                      nfolds = 4,
                      alpha = 1)

# print coeffiencts
coefs <- as.matrix(coef(fit2Full, s = "lambda.min")) %>% as.data.frame()
coefs <- coefs[-1, , drop = F]
coefs <- coefs[c(abs(coefs$s1) > 0), , drop = F] %>% rownames_to_column()
colnames(coefs) <- c("cytokine", "coef")
coefs <- coefs %>% arrange(desc(coef))
coefs2 <- coefs %>% .$cytokine
coefs2


df <- rna.metab.flow.df[coefs2,] |> 
  rownames_to_column('id') |> 
  left_join(as.data.frame(rowData(metab.se)) |> 
              rownames_to_column('id') |> 
              select(id, PLOT_NAME)) |> 
  mutate(id = ifelse(is.na(PLOT_NAME), id, PLOT_NAME)) |> 
  select(-PLOT_NAME) |> 
  column_to_rownames('id')

spike.titer <- subset.patients |> 
  mutate(log10_sarscov2_spike = log10(`SARS-CoV2 Spike`)) |> 
  arrange(`SARS-CoV2 Spike`)

ds.vector <- ifelse(spike.titer$ds == 'no', 'non-DS', 'DS')

col_fun = circlize::colorRamp2(seq(4, 6.5, length = 100), viridis::inferno(100, direction = -1))

ha = HeatmapAnnotation(Group = ds.vector, 
                       `SARS-CoV2 Spike` = spike.titer$log10_sarscov2_spike,
                       col = list(Group = c("DS" = "yellow", "non-DS" = "darkblue"),
                                  `SARS-CoV2 Spike` = col_fun))

draw(Heatmap(name = 'z-score', t(scale(t(df[,spike.titer$sampleid]))), 
        cluster_columns = F, show_column_names = F, top_annotation = ha, 
        row_split = 2, row_names_gp = gpar(fontsize = 7), width = unit(7, 'cm'), 
        height = unit(7, 'cm')), 
     heatmap_legend_side = 'left',
     annotation_legend_side = "bottom")


```


